<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>YesComercialRealStateRadioButton</name>
   <tag></tag>
   <elementGuidId>4fa56594-d16c-420f-996d-76030d67ff00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='own-commercial-real-estate-options']/li/div[2]/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;own-commercial-real-estate-options&quot;)/li[@class=&quot;ads-DefaultListItem__list-item--1WBpN ads-RadioButtonListItem__list-item-radio-reverse--sGZoH form_own-comercial-list__3THp_ form_form-list__11UeS form_small__1za6a&quot;]/div[@class=&quot;ads-DefaultListItem__list-item-selected-marker--1KxZC&quot;]/div[@class=&quot;ads-RadioButtonListItem__radio-container--3I2ND&quot;]/span[@class=&quot;ads-RadioButtonListItem__radio-check--9i1Si&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[role=&quot;option&quot;]:nth-child(1) span[class*=&quot;ads-RadioButtonListItem__radio-check&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ads-RadioButtonListItem__radio-check--9i1Si</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;own-commercial-real-estate-options&quot;)/li[@class=&quot;ads-DefaultListItem__list-item--1WBpN ads-RadioButtonListItem__list-item-radio-reverse--sGZoH form_own-comercial-list__3THp_ form_form-list__11UeS form_small__1za6a&quot;]/div[@class=&quot;ads-DefaultListItem__list-item-selected-marker--1KxZC&quot;]/div[@class=&quot;ads-RadioButtonListItem__radio-container--3I2ND&quot;]/span[@class=&quot;ads-RadioButtonListItem__radio-check--9i1Si&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='own-commercial-real-estate-options']/li/div[2]/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
   </webElementXpaths>
</WebElementEntity>
