<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>continueToHomepageButton</name>
   <tag></tag>
   <elementGuidId>1a330a9f-8163-4fa8-8887-ac89e388fc90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[category = 'primary'][type = 'button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>category</name>
      <type>Main</type>
      <value>primary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ads-PrimaryButton__button--primary--3E7Wi ads-DefaultButton__button--2YzZH ads-DefaultButton__button--large--3enpk button_button__58Y2e button_button-primary__3FrvG form_button__3SJ_2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue to homepage</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;formContainer_form-page-container__s2S4Q ads-Grid__codelitt-container-fluid--2YJJx&quot;]/div[@class=&quot;ads-Grid__codelitt-row--1bLN7 formContainer_form-page-row__2Zk_w&quot;]/div[@class=&quot;ads-Grid__codelitt-col-xxs-3--1tyJK ads-Grid__codelitt-col-xs-3--Logvj ads-Grid__codelitt-col-sm-6--9njP6 ads-Grid__codelitt-col-md-7--H-2qK ads-Grid__codelitt-col-lg-9--3Hu0G ads-Grid__codelitt-col-xl-9--388Ju ads-Grid__codelitt-col-xxl-9--97dbs formContainer_children-container__1D4pK&quot;]/div[@class=&quot;form_container__i1IQq&quot;]/div[@class=&quot;form_buttons-container__c3HBO&quot;]/button[@class=&quot;ads-PrimaryButton__button--primary--3E7Wi ads-DefaultButton__button--2YzZH ads-DefaultButton__button--large--3enpk button_button__58Y2e button_button-primary__3FrvG form_button__3SJ_2&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Commercial Loan Advisor, Beau Eckstein, is going to text you momentarily!'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.findthebank.com'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Continue to homepage' or . = 'Continue to homepage')]</value>
   </webElementXpaths>
</WebElementEntity>
