<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>homeTitle</name>
   <tag></tag>
   <elementGuidId>a54b6781-0e11-4b4a-a243-9038ca92cf36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root-container']/div[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.flowssectionform_header-title__gem0n</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ads-Grid__codelitt-col-xs-4--C10De ads-Grid__codelitt-col-sm-8--25TrQ ads-Grid__codelitt-col-md-12--37jU- ads-Grid__codelitt-col-lg-12--2ga5T ads-Grid__codelitt-col-xl-12--1sflz ads-Grid__codelitt-col-xxl-12--2a5Y_ flowssectionform_header-col-form__1vB7o</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Let's get your project funded!Give us a bit more info on your needs by completing four easy steps.Enter your full nameNext</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root-container&quot;)/div[@class=&quot;ads-Grid__codelitt-row--1bLN7 flowssectionform_header-row__ODK1U&quot;]/div[@class=&quot;flowssectionform_header-row-div__13Zip&quot;]/div[@class=&quot;ads-Grid__codelitt-col-xs-4--C10De ads-Grid__codelitt-col-sm-8--25TrQ ads-Grid__codelitt-col-md-12--37jU- ads-Grid__codelitt-col-lg-12--2ga5T ads-Grid__codelitt-col-xl-12--1sflz ads-Grid__codelitt-col-xxl-12--2a5Y_ flowssectionform_header-col-form__1vB7o&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root-container']/div[3]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We’re getting to work on your deal'])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get a Loan'])[2]/following::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Let&quot; , &quot;'&quot; , &quot;s get your project funded!Give us a bit more info on your needs by completing four easy steps.Enter your full nameNext&quot;) or . = concat(&quot;Let&quot; , &quot;'&quot; , &quot;s get your project funded!Give us a bit more info on your needs by completing four easy steps.Enter your full nameNext&quot;))]</value>
   </webElementXpaths>
</WebElementEntity>
