<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>multifamily</name>
   <tag></tag>
   <elementGuidId>ad0604bc-41e4-40be-a4a4-82b8d21e58f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Multifamily' or . = 'Multifamily')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Multifamily + label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div/div/div[2]/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ads-SelectItemsList__input-container-label--3VUTG buttonsSelectorList_select-items-list__4rpG3 form_primary-asset-options-buttons-list__2xwOE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>Multifamily</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Multifamily</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;formContainer_form-page-container__s2S4Q ads-Grid__codelitt-container-fluid--2YJJx&quot;]/div[@class=&quot;ads-Grid__codelitt-row--1bLN7 formContainer_form-page-row__2Zk_w&quot;]/div[@class=&quot;ads-Grid__codelitt-col-xxs-3--1tyJK ads-Grid__codelitt-col-xs-3--Logvj ads-Grid__codelitt-col-sm-6--9njP6 ads-Grid__codelitt-col-md-7--H-2qK ads-Grid__codelitt-col-lg-9--3Hu0G ads-Grid__codelitt-col-xl-9--388Ju ads-Grid__codelitt-col-xxl-9--97dbs formContainer_children-container__1D4pK&quot;]/div[@class=&quot;form_container__i1IQq&quot;]/div[1]/div[@class=&quot;buttonsSelectorList_buttons-selector-container__2wC5J form_primary-asset-options-buttons-list__2xwOE ads-Grid__codelitt-container-fluid--2YJJx&quot;]/div[@class=&quot;ads-Grid__codelitt-row--1bLN7&quot;]/div[@class=&quot;ads-SelectItemsList__container--2MfOx buttonsSelectorList_select-items-list__4rpG3 form_primary-asset-options-buttons-list__2xwOE&quot;]/div[1]/label[@class=&quot;ads-SelectItemsList__input-container-label--3VUTG buttonsSelectorList_select-items-list__4rpG3 form_primary-asset-options-buttons-list__2xwOE&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div/div[2]/div/div/div/label</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Great! Now let', &quot;'&quot;, 's dive into your project.')])[1]/following::label[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::label[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/label</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Multifamily' or . = 'Multifamily')]</value>
   </webElementXpaths>
</WebElementEntity>
